/**
 * Canonical Tomcat BP template schema (Zod).
 * Auto-generated by scripts/extract-bp-template-spec.mjs — do not edit by hand.
 * Regenerate: npm run extract:bp-template
 */
import { z } from "zod";

export const BP_TEMPLATE_SOURCE = {
  driveFileId: "1iE3sfRF-oyGXp11BO9Uxn7xH-f--Oxo2",
  driveFileName: "MAJ Template BP SaaS.xlsx",
  driveFolder: "05. Templates BP",
  sharedDriveId: "0AO2MAh9ncUDNUk9PVA",
  contentSha256: "2a441f87eb26bcc30ad466bdb36bc3dc4717952692dad89ebbe0e77f852e1567",
  extractedAt: "2026-05-24",
  tabCount: 12,
} as const;

export const BP_CANONICAL_TAB_NAMES = [
  "Input Réalisé",
  "Input Prévisionnel",
  "CA",
  "AACE",
  "RH",
  "Financement",
  "P&L ",
  "Plan de trésorerie",
  "BPI-Plan de tréso",
  "BPI - compte de résultat prévis",
  "BPI - Plan de financement",
  "Tableaux Dossiers",
] as const;

export type BpCanonicalTabName = (typeof BP_CANONICAL_TAB_NAMES)[number];

export const BP_TAB_SLUGS = {
  "Input Réalisé": "input_realise",
  "Input Prévisionnel": "input_previsionnel",
  "CA": "ca",
  "AACE": "aace",
  "RH": "rh",
  "Financement": "financement",
  "P&L ": "pl",
  "Plan de trésorerie": "plan_tresorerie",
  "BPI-Plan de tréso": "bpi_plan_treso",
  "BPI - compte de résultat prévis": "bpi_pl",
  "BPI - Plan de financement": "bpi_plan_financement",
  "Tableaux Dossiers": "tableaux_dossiers",
} as const;

export type BpTabSlug = (typeof BP_TAB_SLUGS)[BpCanonicalTabName];

export const BpTabSlugSchema = z.enum([
  "input_realise",
  "input_previsionnel",
  "ca",
  "aace",
  "rh",
  "financement",
  "pl",
  "plan_tresorerie",
  "bpi_plan_treso",
  "bpi_pl",
  "bpi_plan_financement",
  "tableaux_dossiers",
]);

export const BpTemplateMetaSchema = z.object({
  source: z.object({
    driveFileId: z.string(),
    driveFileName: z.string(),
    driveFolder: z.string(),
    sharedDriveId: z.string(),
    contentSha256: z.string().regex(/^[a-f0-9]{64}$/),
  }),
  extractedAt: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
  tabCount: z.literal(12),
});

export const BpRevenuePatternSchema = z.enum([
  "monthly_mrr_multi_offer",
  "annual_subscription",
  "usage_based",
  "custom",
]);

export const BpFinancingInstrumentTypeSchema = z.enum([
  "equity_raise",
  "quasi_equity",
  "private_loan",
  "public_grant",
]);

const financingBase = { label: z.string().min(1) };

export const BpFinancingEquityRowSchema = z.object({
  ...financingBase,
  instrumentType: z.literal("equity_raise"),
  subscriptionDate: z.number().optional(),
  amount: z.number().optional(),
}).strict();

export const BpFinancingQuasiEquityRowSchema = z.object({
  ...financingBase,
  instrumentType: z.literal("quasi_equity"),
  subscriptionDate: z.number().optional(),
  amount: z.number().optional(),
}).strict();

export const BpFinancingPrivateLoanRowSchema = z.object({
  ...financingBase,
  instrumentType: z.literal("private_loan"),
  subscriptionDate: z.number().optional(),
  amount: z.number(),
  repaymentYears: z.number().optional(),
  annualRate: z.number().min(0).max(1).optional(),
  graceMonths: z.number().optional(),
  firstPaymentPct: z.number().min(0).max(1).optional(),
}).strict();

export const BpFinancingPublicGrantRowSchema = z.object({
  ...financingBase,
  instrumentType: z.literal("public_grant"),
  subscriptionDate: z.number().optional(),
  amount: z.number(),
  grantPortion: z.number().optional(),
  repaymentYears: z.number().optional(),
  annualRate: z.number().min(0).max(1).optional(),
  graceMonths: z.number().optional(),
  projectMonths: z.number().optional(),
}).strict();

export const BpFinancingInstrumentRowSchema = z.discriminatedUnion("instrumentType", [
  BpFinancingEquityRowSchema,
  BpFinancingQuasiEquityRowSchema,
  BpFinancingPrivateLoanRowSchema,
  BpFinancingPublicGrantRowSchema,
]);

export const BpFinancementTabDraftSchema = z.object({
  tabSlug: z.literal("financement"),
  instruments: z.array(BpFinancingInstrumentRowSchema).min(1),
});

/** Founder BP debt tab (e.g. eSwit « Debt »): monthly schedule, not instrument grid. */
export const FounderDebtPaymentRowSchema = z.object({
  periodIndex: z.number().int().optional(),
  principal: z.number().optional(),
  interest: z.number().optional(),
  payment: z.number().optional(),
  balanceEnd: z.number().optional(),
});

export const FounderDebtInstrumentSchema = z.object({
  label: z.string().min(1),
  sourceTab: z.string().optional(),
  subscriptionDate: z.union([z.number(), z.string()]).optional(),
  amount: z.number().optional(),
  annualRate: z.number().min(0).max(1).optional(),
  termMonths: z.number().int().optional(),
  schedule: z.array(FounderDebtPaymentRowSchema).optional(),
});

export const BpOfferPricingSchema = z.object({
  offerIndex: z.number().int().min(1).max(4),
  monthlyPricing: z.number().optional(),
  setupFee: z.number().optional(),
});

export const BpInputPrevisionnelSchema = z.object({
  cashBalanceDate: z.number().optional(),
  openingCashAmount: z.number().optional(),
  firstYearOfActivity: z.boolean().optional(),
  forecastStartDate: z.number().optional(),
  vatRate: z.number().min(0).max(1).optional(),
  offers: z.array(BpOfferPricingSchema).max(4).optional(),
});

export const BpWorkflowModeSchema = z.enum(["transform", "generate", "hybrid"]);

export const BP_CANONICAL_TAB_NAME_SET: ReadonlySet<string> = new Set(BP_CANONICAL_TAB_NAMES);

export const BP_CANONICAL_DETECTION_TABS = [
  "Input Réalisé",
  "Input Prévisionnel",
  "CA",
  "AACE",
  "RH",
  "Financement",
  "P&L ",
  "Plan de trésorerie",
] as const satisfies readonly BpCanonicalTabName[];

export function normalizeBpTabName(raw: string): string {
  const trimmed = raw.trim();
  if (/^p&l\s*$/i.test(trimmed)) return "P&L ";
  return trimmed;
}

export function resolveCanonicalTabName(raw: string): BpCanonicalTabName | undefined {
  const normalized = normalizeBpTabName(raw);
  if (BP_CANONICAL_TAB_NAME_SET.has(normalized)) {
    return normalized as BpCanonicalTabName;
  }
  const lower = normalized.toLowerCase();
  for (const name of BP_CANONICAL_TAB_NAMES) {
    if (name.toLowerCase() === lower) return name;
  }
  return undefined;
}

export function countCanonicalDetectionTabs(sheetNames: readonly string[]): {
  hits: number;
  total: number;
  isCanonical: boolean;
} {
  const resolved = new Set(
    sheetNames
      .map((n) => resolveCanonicalTabName(n))
      .filter((n): n is BpCanonicalTabName => n !== undefined),
  );
  let hits = 0;
  for (const tab of BP_CANONICAL_DETECTION_TABS) {
    if (resolved.has(tab)) hits += 1;
  }
  return {
    hits,
    total: BP_CANONICAL_DETECTION_TABS.length,
    isCanonical: hits === BP_CANONICAL_DETECTION_TABS.length,
  };
}

export type BpFinancingInstrumentType = z.infer<typeof BpFinancingInstrumentTypeSchema>;
export type BpFinancingInstrumentRow = z.infer<typeof BpFinancingInstrumentRowSchema>;
export type BpFinancementTabDraft = z.infer<typeof BpFinancementTabDraftSchema>;
export type FounderDebtInstrument = z.infer<typeof FounderDebtInstrumentSchema>;
export type BpInputPrevisionnel = z.infer<typeof BpInputPrevisionnelSchema>;
export type BpWorkflowMode = z.infer<typeof BpWorkflowModeSchema>;
